# Generated by Django 2.2 on 2022-04-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name',), 'verbose_name': 'products', 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='categ',
            old_name='imge',
            new_name='img',
        ),
    ]
