# Generated by Django 2.2 on 2022-04-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220428_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categ',
            old_name='imge',
            new_name='img',
        ),
    ]
