# Generated by Django 2.2 on 2022-04-30 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220428_1836'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='items',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.cartlist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='prodt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='quan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
