# Generated by Django 2.2 on 2022-04-30 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220430_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartlist'),
        ),
    ]
